#!/bin/bash

echo "=== PythonAnywhere AGTDesigner Setup ==="
echo ""
echo "Follow these steps on PythonAnywhere:"
echo ""
echo "1. Open PythonAnywhere Bash Console"
echo "2. Navigate to your home directory:"
echo "   cd ~"
echo ""
echo "3. Clear any existing Git credentials:"
echo "   git config --global --unset credential.helper"
echo "   rm ~/.git-credentials 2>/dev/null"
echo "   git config --global credential.helper \"\""
echo ""
echo "4. Clone the AGTDesigner repository:"
echo "   git clone https://github.com/leruseadam/AGTDesigner.git"
echo ""
echo "5. When prompted for credentials:"
echo "   Username: leruseadam"
echo "   Password: [Your GitHub Personal Access Token]"
echo ""
echo "6. Navigate into the repository:"
echo "   cd AGTDesigner"
echo ""
echo "7. Verify the setup:"
echo "   git status"
echo "   git log --oneline -3"
echo ""
echo "8. If you need to set up the web app:"
echo "   - Go to Web tab on PythonAnywhere"
echo "   - Add a new web app"
echo "   - Choose Manual configuration"
echo "   - Set source code to: /home/YOUR_USERNAME/AGTDesigner"
echo ""
echo "9. Set up virtual environment:"
echo "   python3 -m venv agtdesigner-env"
echo "   source agtdesigner-env/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "=== Alternative: If Git doesn't prompt for credentials ==="
echo ""
echo "Use the token directly in the URL:"
echo "git clone https://leruseadam:YOUR_TOKEN@github.com/leruseadam/AGTDesigner.git"
echo ""
echo "Replace YOUR_TOKEN with your actual Personal Access Token" 