#!/bin/bash

echo "=== PythonAnywhere SSH Setup Script ==="
echo ""
echo "Follow these steps on PythonAnywhere:"
echo ""
echo "1. Go to PythonAnywhere.com and log in"
echo "2. Go to the 'Account' page"
echo "3. Scroll down to 'SSH keys' section"
echo "4. Add your SSH public key:"
echo ""
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDXQ/NRzexq4Aq2gqws5iIwNuNxKXbFHggVhKbF6IDfI leruseadam@gmail.com"
echo ""
echo "5. Save the key"
echo ""
echo "6. Then in PythonAnywhere bash console, run:"
echo "   git clone git@github.com:leruseadam/AGTDesigner.git"
echo ""
echo "7. If you need to change an existing repo from HTTPS to SSH:"
echo "   git remote set-url origin git@github.com:leruseadam/AGTDesigner.git"
echo ""
echo "This will use SSH authentication instead of HTTPS." 